# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:

    environment:
      CC_TEST_REPORTER_ID: 5d3d308e4b004007b0fb88945513b93bab1a6222cc989413820e44ce740824a1

    docker:
      - image: circleci/golang:1.15

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps:
      - checkout

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Install dependencies
          command: go get -t -v ./...

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            go test -coverprofile c.out ./...
            ./cc-test-reporter after-build -p $(go list -m) --exit-code $?
